# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name highest_quarter
#' @title Temperature Of The Highest Quarter
#' @param x matrix of timeseries.
#' @return matrix with average temperature of the highest quarter (first
#'   column) and the first month of the quarter (second column).
highest_quarter <- function(x) {
    .Call(`_squirrygis_highest_quarter`, x)
}

#' @name lowest_quarter
#' @title Temperature Of The Lowest Quarter
#' @param x matrix of timeseries.
#' @return matrix with average temperature of the lowest quarter (first
#'   column) and the first month of the quarter (second column).
lowest_quarter <- function(x) {
    .Call(`_squirrygis_lowest_quarter`, x)
}

