# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name bio08
#' @title Average Value of the Wettest Quarter
#' @param tas matrix of averate temperature timeseries.
#' @param pr matrix of precipitaiton timeseries.
#' @return matrix with average temperature of the highest quarter (first
#'   column) and the first month of the quarter (second column).
cpp_bio08 <- function(tas, pr) {
    .Call(`_squirrygis_cpp_bio08`, tas, pr)
}

#' @name highest_quarter
#' @title Average Value of the Highest Quarter
#' @param x matrix of timeseries.
#' @return matrix with average climate of the highest quarter (first
#'   column) and the first month of the quarter (second column).
highest_quarter <- function(x) {
    .Call(`_squirrygis_highest_quarter`, x)
}

#' @name lowest_quarter
#' @title Average Value of the Lowest Quarter
#' @param x matrix of timeseries.
#' @return matrix with average temperature of the lowest quarter (first
#'   column) and the first month of the quarter (second column).
lowest_quarter <- function(x) {
    .Call(`_squirrygis_lowest_quarter`, x)
}

